### ISSUE TITLE
Comment out things that do not exist yet

### ISSUE THREAD

**Issue by craigfisk** [Marmalade-ai/company-website#91]
`Terms of Service` page link and `Social Media` links for `Github` and `Linkedin`. There is a [Linkedin page](https://www.linkedin.com/company/marmalade-ai) but [Twitter](https://twitter.com/MarmaladeAI) will be the focus for the next period, so it seems like these could all just be commented out for now.

## Tasks

- [x] Remove `Terms of Service` page and associated link in `Policies` section of the Footer. When we have content for that page, it will be re-implemented through Issue #100.
- [x] Remove the `GitHub` link in the `Social Media` section of the Footer. We may choose to add that link back again after completing Issue #99.
- [x] Remove the `LinkedIn` link in the `Social Media` section of the Footer. We may choose to add that link back again after completing Issue #101.

## Related Issues
* The `Choosing a Plan` table on the home page will be removed as part of Issue #93. That can be done independent of the tasks listed above.
