### ISSUE TITLE
Clean up the public view of `github.com/Marmalade-ai`

### ISSUE THREAD

**Issue by jimtyhurst** [Marmalade-ai/company-website#99]
Clean up the public view of https://github.com/Marmalade-ai/ before implementing a `GitHub` link in the `Social Media` section of the Footer.

## Tasks
- [ ] @craigfisk : Change https://github.com/Marmalade-ai/Vue-Firebase-Auth-Tutorial to be a private repository or move it to your personal GitHub account.
- [ ] @craigfisk : Change https://github.com/Marmalade-ai/quickstart-testing to be a private repository or move it to your personal GitHub account.
- [ ] Do we need the [Marmalade-ai/pydiscourse](https://github.com/Marmalade-ai/pydiscourse) fork of [bennylope/pydiscourse](https://github.com/bennylope/pydiscourse)?
- [ ] Do we need the [Marmalade-ai/discourse](https://github.com/Marmalade-ai/discourse) fork of [discourse/discourse](https://github.com/discourse/discourse)? Our fork is way behind the source repository. Is there anything unique on our fork that we should keep?
- [ ] Add a `GitHub` link to the `Social Media` section of the Footer.
